/**
 * IPC Constants for Supervisor-Worker Communication
 */

export const IPC_METHODS = {
  HEALTH_CHECK: 'health_check',
  MCP_TOOL: 'mcp_tool',
  SHUTDOWN: 'shutdown',
  READY: 'ready',
  ERROR: 'error',
} as const;

export const IPC_ERROR_CODES = {
  INTERNAL_ERROR: -32603,
  INVALID_REQUEST: -32600,
  METHOD_NOT_FOUND: -32601,
  INVALID_PARAMS: -32602,
  TIMEOUT: -32000,
  WORKER_NOT_AVAILABLE: -32001,
  WORKER_CRASHED: -32002,
} as const;

export const SUPERVISOR_DEFAULTS = {
  MAX_RESTART_ATTEMPTS: 5,
  RESTART_DELAY_MS: 2000,
  HEALTH_CHECK_INTERVAL_MS: 30000,
  HEALTH_CHECK_TIMEOUT_MS: 5000,
  REQUEST_TIMEOUT_MS: 30000,
  CONSECUTIVE_FAILURES_BEFORE_RESTART: 3,
} as const;

export const SUPERVISOR_ENV_KEYS = {
  ENABLED: 'SUPERVISOR_ENABLED',
  MAX_RESTART_ATTEMPTS: 'SUPERVISOR_MAX_RESTART_ATTEMPTS',
  RESTART_DELAY_MS: 'SUPERVISOR_RESTART_DELAY_MS',
  HEALTH_CHECK_INTERVAL_MS: 'SUPERVISOR_HEALTH_CHECK_INTERVAL_MS',
  HEALTH_CHECK_TIMEOUT_MS: 'SUPERVISOR_HEALTH_CHECK_TIMEOUT_MS',
} as const;
